- id: '1578161087836'
  alias: Wyącz lampę
  description: ''
  trigger:
  - at: '23:02'
    platform: time
  - at: '7:35'
    platform: time
  condition: []
  action:
  - device_id: b0939001fa8447dba8f7bc4409c3d844
    domain: switch
    entity_id: switch.lamp
    type: turn_off
- id: '1578162711347'
  alias: Włącz lampę
  description: ''
  trigger:
  - event: sunset
    platform: sun
  condition: []
  action:
  - device_id: b0939001fa8447dba8f7bc4409c3d844
    domain: switch
    entity_id: switch.lamp
    type: turn_on
