- id: '1578161087836'
  alias: Wylacz oswietlenie front
  description: ''
  trigger:
  - at: '22:00'
    platform: time
  condition: []
  action:
  - device_id: b0939001fa8447dba8f7bc4409c3d844
    domain: light
    entity_id: light.gateway2light11
    type: turn_off
- id: '1578162711347'
  alias: Wlacz oswietlenie front
  description: ''
  trigger:
  - at: '19:00'
    platform: time
  condition: []
  action:
  - device_id: b0939001fa8447dba8f7bc4409c3d844
    domain: light
    entity_id: light.gateway2light11
    type: turn_on

- alias: 'Włącz choinkę'
  trigger:
    platform: sun
    event: sunset
  condition: []
  action:
    service: switch.turn_on
    entity_id: switch.wallplug1

- alias: 'Wyłącz choinkę'
  trigger:
    at: '23:00'
    platform: time
  condition: []
  action:
    service: switch.turn_off
    entity_id: switch.wallplug1