
# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# Uncomment this if you are using SSL/TLS, running in Docker container, etc.
# http:
#   base_url: example.duckdns.org:8123

# Text to speech
tts:
  - platform: google_translate

weather:
  - platform: openweathermap
    api_key: !secret openweathermap_password

homeassistant:
  name: Nasz Dom
  latitude: 50.348172
  longitude: 20.046405
  elevation: 300
  unit_system: metric
  time_zone: Europe/Warsaw
  customize: !include customize.yaml
  customize_domain:
    light:
      assumed_state: false
    switch:
      assumed_state: false

lovelace:
  mode: yaml

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
switch: !include switch.yaml
sensor: !include sensor.yaml
climate: !include climate.yaml
light: !include light.yaml

camera:
  - platform: ffmpeg
    name: wjazd
    input: rtsp://192.168.100.138:554

mqtt:
  broker: 192.168.100.151
  protocol: 3.1.1
  keepalive: 60
  client_id: dom-prd
  username: mqtt
  password: mqtt

influxdb:
  host: 192.168.100.151
  username: homeassistant
  password: homeassistant
  include:
    entities:
       - sensor.openweathermap_temperature
       - sensor.pv_outputpower
       - sensor.pv_eday
       - sensor.pv_etotal

logger:
  default: info
  logs:
    homeassistant.components.stream.worker: fatal
