- platform: mqtt
  state_topic: "/mqtt-gateway-1/temp-1"
  name: "garagetemp"
  unit_of_measurement: '°C'
  value_template: "{{ value_json.temperature }}"

- platform: mqtt
  state_topic: "tele/temp-liv-room-win/SENSOR"
  name: "livingroomwindowstemp"
  unit_of_measurement: '°C'
  value_template: "{{ value_json['DS18B20']['Temperature'] }}"

- platform: mqtt
  state_topic: "/mqtt-gateway-3/temp-1"
  name: "officetemp"
  unit_of_measurement: '°C'
  value_template: "{{ value_json.temperature }}"

- platform: sems
  username: !secret sems_email
  password: !secret sems_password
  station_id: !secret sems_station 
  scan_interval: 60

# A template to ease access to the data as "sensor.pv_outputpower" etc.
- platform: template
  sensors:
    pv_outputpower:
      value_template: '{{ states.sensor.sems_portal.attributes.outputpower }}'
      unit_of_measurement: 'W'
      friendly_name: "PV Power output"
    pv_temperature:
      value_template: '{{ states.sensor.sems_portal.attributes.tempperature }}'
      unit_of_measurement: 'C'
      friendly_name: "PV Temperature"
    pv_eday:
      value_template: '{{ states.sensor.sems_portal.attributes.eday }}'
      unit_of_measurement: 'kWh'
      friendly_name: "PV energy day"
    pv_etotal:
      value_template: '{{ states.sensor.sems_portal.attributes.etotal }}'
      unit_of_measurement: 'kWh'
      friendly_name: "PV energy total"
    pv_iday:
      value_template: '{{ states.sensor.sems_portal.attributes.iday }}'
      unit_of_measurement: '€'
      friendly_name: "PV income day"
    pv_itotal:
      value_template: '{{ states.sensor.sems_portal.attributes.itotal }}'
      unit_of_measurement: '€'
      friendly_name: "PV income total"