- platform: mqtt
  name: "regal"
  state_topic: "/smart-item-1/socket-1/state"
  command_topic: "/smart-item-1/socket-1/cmd"
  optimistic: true
  payload_on: "on"
  payload_off: "off"
  qos: 1
  retain: true

- platform: mqtt
  name: "lamp"
  state_topic: "stat/wallplug-1/POWER"
  command_topic: "cmnd/wallplug-1/POWER"
  optimistic: true
  payload_on: "ON"
  payload_off: "OFF"
  qos: 1
  retain: true