- platform: mqtt
  name: "heatinglrwindows"
  state_topic: "/mqtt-gateway-1/heating-14/state"
  command_topic: "/mqtt-gateway-1/heating-14/cmd"
  optimistic: true
  payload_on: "on"
  payload_off: "off"
  qos: 1
  retain: true

- platform: mqtt
  name: "heatinglrkitchen"
  state_topic: "/mqtt-gateway-1/heating-15/state"
  command_topic: "/mqtt-gateway-1/heating-15/cmd"
  optimistic: true
  payload_on: "on"
  payload_off: "off"
  qos: 1
  retain: true

- platform: mqtt
  name: "heatinggarage"
  state_topic: "/mqtt-gateway-1/heating-16/state"
  command_topic: "/mqtt-gateway-1/heating-16/cmd"
  optimistic: true
  payload_on: "on"
  payload_off: "off"
  qos: 1
  retain: true

- platform: mqtt
  name: "heatingbathroomground"
  state_topic: "/mqtt-gateway-1/heating-17/state"
  command_topic: "/mqtt-gateway-1/heating-17/cmd"
  optimistic: true
  payload_on: "on"
  payload_off: "off"
  qos: 1
  retain: true