switch.shenzhen_neo_electronics_co_ltd_power_plug_12a_switch:
  ignored: false
  polling_intensity: 0
switch.shenzhen_neo_electronics_co_ltd_power_plug_12a_switch_2:
  ignored: false
  polling_intensity: 0
